"""youtube channels

Revision ID: 3e20201a4409
Revises: 98236fc8f4e3
Create Date: 2026-07-03 19:06:47.952580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e20201a4409'
down_revision: Union[str, None] = '98236fc8f4e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('youtube_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.String(length=64), nullable=False),
    sa.Column('handle', sa.String(length=128), nullable=False),
    sa.Column('display_name', sa.String(length=256), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('youtube_channels', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_youtube_channels_channel_id'), ['channel_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('youtube_channels', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_youtube_channels_channel_id'))

    op.drop_table('youtube_channels')
    # ### end Alembic commands ###
