"""initial schema: medallion + portfolio

Revision ID: 98236fc8f4e3
Revises: 
Create Date: 2026-06-14 12:32:32.659996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98236fc8f4e3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=64), nullable=False),
    sa.Column('country', sa.String(length=64), nullable=False),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assets_ticker'), ['ticker'], unique=True)

    op.create_table('bronze_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_table', sa.String(length=64), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('dedupe_key', sa.String(length=256), nullable=False),
    sa.Column('payload', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bronze_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bronze_records_dedupe_key'), ['dedupe_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_bronze_records_source_table'), ['source_table'], unique=False)
        batch_op.create_index(batch_op.f('ix_bronze_records_status'), ['status'], unique=False)

    op.create_table('metrics_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('portfolio_value', sa.Float(), nullable=False),
    sa.Column('daily_return', sa.Float(), nullable=False),
    sa.Column('cumulative_return', sa.Float(), nullable=False),
    sa.Column('drawdown', sa.Float(), nullable=False),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('sharpe', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date', name='uq_metrics_snapshot_date')
    )
    with op.batch_alter_table('metrics_daily', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_metrics_daily_snapshot_date'), ['snapshot_date'], unique=False)

    op.create_table('quarantine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_table', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', sa.Text(), nullable=False),
    sa.Column('failed_check', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('quarantine', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quarantine_source_table'), ['source_table'], unique=False)

    op.create_table('transcripts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_channel', sa.String(length=128), nullable=False),
    sa.Column('video_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('video_id', name='uq_transcript_video')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('sentiment', sa.Float(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url', name='uq_news_url')
    )
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_news_asset_id'), ['asset_id'], unique=False)

    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('avg_cost', sa.Float(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_positions_asset_id'), ['asset_id'], unique=False)

    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('ingested_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'date', name='uq_price_asset_date')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prices_asset_id'), ['asset_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_prices_date'), ['date'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=8), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('fee', sa.Float(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_asset_id'), ['asset_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_asset_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prices_date'))
        batch_op.drop_index(batch_op.f('ix_prices_asset_id'))

    op.drop_table('prices')
    with op.batch_alter_table('positions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_positions_asset_id'))

    op.drop_table('positions')
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_news_asset_id'))

    op.drop_table('news')
    op.drop_table('transcripts')
    with op.batch_alter_table('quarantine', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quarantine_source_table'))

    op.drop_table('quarantine')
    with op.batch_alter_table('metrics_daily', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_metrics_daily_snapshot_date'))

    op.drop_table('metrics_daily')
    with op.batch_alter_table('bronze_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bronze_records_status'))
        batch_op.drop_index(batch_op.f('ix_bronze_records_source_table'))
        batch_op.drop_index(batch_op.f('ix_bronze_records_dedupe_key'))

    op.drop_table('bronze_records')
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assets_ticker'))

    op.drop_table('assets')
    # ### end Alembic commands ###
